apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xybx5h5xw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xybx5h5xw-nodejs 
  name: xybx5h5xw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xybx5h5xw-nodejs 
